# ~/.config/starship.toml

# Use custom format
format = """
[$status$git_status](bold green)$directory$battery
[emoon @ âœ](bold green) """

right_format = """$all"""

# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 10

# Disable the blank line at the start of the prompt
add_newline = true

[git_status]
conflicted = "ïŠ–"
ahead = "ïŠ–ğŸ’¨"
behind = " "
diverged = " "
up_to_date = "âœ“"
untracked = "ïŠ–"
stashed = " "
#stashed = "ğŸ“¦"
modified = " "
staged = '[++\($count\)](green)'
renamed = " "
deleted = "ïŠ–"

[status]
style = "bg:blue"
symbol = " "
format = '[\[$symbol $common_meaning$signal_name$maybe_int\]]($style) '
map_symbol = true
disabled = false

[battery]
full_symbol = "  "
charging_symbol = "âš¡ï¸ "
discharging_symbol = "  "

[[battery.display]] # "bold red" style and discharging_symbol when capacity is between 0% and 10%
threshold = 10
style = "bold red"

[[battery.display]] # "bold yellow" style and ğŸ’¦ symbol when capacity is between 10% and 30%
threshold = 60
style = "bold yellow"
discharging_symbol = " "

[[battery.display]] # "bold yellow" style and ğŸ’¦ symbol when capacity is between 10% and 30%
threshold = 90
style = "bold green"
discharging_symbol = " "

[python]
symbol = "îœ¼ "

[lua]
symbol = "î˜  "

[aws]
symbol = "îŒ½  "

[buf]
symbol = "ï’ "

[conda]
symbol = "ï„Œ "

[dart]
symbol = "î˜ "

[directory]
read_only = " ï ½"
home_symbol = "ïŒƒ"

[docker_context]
symbol = "ïŒˆ "

[elixir]
symbol = "î‰µ "

[elm]
symbol = "î˜¬ "

[git_branch]
symbol = "ï˜ "

[golang]
symbol = "î˜§ "

[haskell]
symbol = "î· "

[hg_branch]
symbol = "ï˜ "

[java]
symbol = "î‰– "

[julia]
symbol = "î˜¤ "

[memory_usage]
symbol = "ï¡š "

[nim]
symbol = "ïš¤ "

[nix_shell]
symbol = "ï‹œ "

[nodejs]
symbol = "îœ˜ "

[package]
symbol = "ï£– "

[rust]
symbol = "î¨ "
